version: "3.10"

name: traffic_analysis_production
services:
  frontend:
    build: ./FrontEnd
    container_name: frontend_prod_c
    ports:
      - '80:80'
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend_prod_c
    ports:
      - '5000:5000'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
