version: "3.10"

name: traffic_analysis
services:
  frontend:
    build: ./FrontEnd
    container_name: frontend_c
    ports:
      - '80:80'
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend_c
    ports:
      - '5000:5000'
      - "1235:1235/udp"
    environment:
      - DISPLAY=<YOUR_LOCAL_IP>:0.0
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
  
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '0.0.0.0:27022:27017'
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./mongo-init/data:/tmp/data
      - ~/dev/mongodb/data/m3:/data/db
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/