version: "3.10"

name: traffic_analysis
services:
  frontend:
    build: ./FrontEnd
    container_name: frontend_c
    ports:
      - '80:80'
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend_c
    ports:
      - '5000:5000'
      - "1235:1235/udp"
    environment:
      - DISPLAY=192.168.1.113:0.0
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
  